FROM python:3.6-alpine3.12

LABEL maintainer = "Web & Apps team <webapps@bas.ac.uk>"

# Setup project
WORKDIR /usr/src/app

ENV PYTHONPATH /usr/src/app
ENV FLASK_APP manage.py
ENV FLASK_ENV development

# Setup project dependencies
COPY requirements.txt /usr/src/app/
RUN apk add --no-cache postgresql-libs libffi-dev libressl-dev python3-dev py-pip && \
    apk add --no-cache --virtual .build-deps build-base linux-headers postgresql-dev
    
COPY requirements.txt /usr/src/app/
    
RUN pip install --upgrade pip && \
    pip install -r requirements.txt --no-cache-dir && \
    apk --purge del .build-deps

# Add application - more complicated because COPY only copies the contents of a directory for some insane reason
COPY arctic_office_projects_api/ /usr/src/app/arctic_office_projects_api/
COPY migrations/ /usr/src/app/migrations/
COPY resources/ /usr/src/app/resources/
COPY config.py manage.py /usr/src/app/

# Setup runtime
ENTRYPOINT []
