FROM python:3.9-alpine as base

LABEL maintainer = "BAS Web Apps <webapps@bas.ac.uk>"

RUN apk add --no-cache \
    libxslt-dev \
    libffi-dev \
    openssl-dev \
    libxml2-utils \
    postgresql-dev

FROM base as poetry

RUN apk add --no-cache build-base cargo
RUN python3 -m pip install pipx
RUN python3 -m pipx install poetry==1.7.1

FROM poetry as run

WORKDIR /usr/src/app

ENV PATH="/venv/bin:/root/.local/bin:$PATH"
COPY pyproject.toml poetry.lock /
RUN poetry config virtualenvs.in-project true
RUN poetry install --no-root --no-interaction --no-ansi
RUN poetry run python -m pip install --upgrade pip

COPY . /usr/src/app/

ENV FLASK_APP manage.py

ENTRYPOINT []