---
version: "2"

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 9000:9000
    env_file:
      - ./.env
    command: poetry run flask run --host 0.0.0.0 --port 9000
    # command: tail -f /dev/null

  app-db:
    image: postgres:11.1-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - 5432:5432

  # To run tests:
  # - switch database containers
  # - switch the env vars for the app

  # app-test-db:
  #   image: postgres:11.1-alpine
  #   volumes:
  #     - postgres_test_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=app
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=app
  #   ports:
  #     - 5432:5432


volumes:
  postgres_volume:
  postgres_test_data:

