---
version: "2"

services:
  app-db:
    image: postgres:11.1-alpine
    volumes:
      - ./docker/postgresql-databases.sql:/docker-entrypoint-initdb.d/postgresql-databases.sql
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - 5432:5432

  app:
    build: .
    image: docker-registry.data.bas.ac.uk/web-apps/arctic-office-projects-api:latest
    command: flask run --host 0.0.0.0 --port 9000
    depends_on:
      - app-db
    volumes:
      - .:/usr/src/app
    ports:
      - 9000:9000
