---
version: "2"

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    command: poetry run flask run --host 0.0.0.0 --port 5000
    # command: tail -f /dev/null
    # network_mode: "host"

  app-db:
    image: postgres:11.1-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    # network_mode: "host"

  # app-test-db:
  #   image: postgres:11.1-alpine
  #   volumes:
  #     - postgres_test_volume:/var/lib/postgresql/data/
  #     - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   environment:
  #     - POSTGRES_USER=app
  #     - POSTGRES_PASSWORD=password
  #     - PGPORT=5433
  #   ports:
  #     - 5433:5433
  #   network_mode: "host"


volumes:
  postgres_volume:
  # postgres_test_volume:

