"""empty message

Revision ID: 0da61d9681b1
Revises: c2f46d74fb33
Create Date: 2022-06-30 14:30:53.419477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da61d9681b1'
down_revision = 'c2f46d74fb33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grants', sa.Column('lead_project', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grants', 'lead_project')
    # ### end Alembic commands ###
