"""empty message

Revision ID: 1b4a4527430b
Revises: 03eddf0b8e79
Create Date: 2024-04-02 11:08:54.994648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4a4527430b'
down_revision = '03eddf0b8e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('grant_reference', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'grant_reference')
    # ### end Alembic commands ###
