"""empty message

Revision ID: 4018d6dfe5b8
Revises: 1b4a4527430b
Create Date: 2025-09-26 10:59:59.418422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4018d6dfe5b8'
down_revision = '1b4a4527430b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Text(), nullable=True),
    sa.Column('organisation_name', sa.Text(), nullable=True),
    sa.Column('organisation_ror', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('gtr_person', sa.Text(), nullable=True),
    sa.Column('orcid', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_text', sa.Text(), nullable=True),
    sa.Column('gcmd_link_code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Text(), nullable=True),
    sa.Column('topic_name', sa.Text(), nullable=True),
    sa.Column('gcmd_link_name', sa.Text(), nullable=True),
    sa.Column('gcmd_link_code', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_topics')
    op.drop_table('project_subjects')
    op.drop_table('project_people')
    op.drop_table('project_organisations')
    # ### end Alembic commands ###
