"""Making Organisation optional

Revision ID: c2f46d74fb33
Revises: fe26d37d220f
Create Date: 2019-12-02 14:07:56.165568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f46d74fb33'
down_revision = 'fe26d37d220f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_categorisations_project_category_term',
                       'categorisations', type_='unique')
    op.alter_column('grants', 'organisation_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('people', 'organisation_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'organisation_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('grants', 'organisation_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.create_unique_constraint('uq_categorisations_project_category_term', 'categorisations', [
                                'project_id', 'category_term_id'])
    # ### end Alembic commands ###
